config/routes.rb
Ouathdemo::Application.routes.draw do
  resources :secrets

  devise_for :users

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  

end

app/models/secret.rb
class Secret < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    return secrets_path
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_secret, only: [:show, :edit, :update, :destroy]

  # GET /secrets
  # GET /secrets.json
  def index
    @secrets = Secret.all
  end

  # GET /secrets/1
  # GET /secrets/1.json
  def show
  end

  # GET /secrets/new
  def new
    @secret = Secret.new
  end

  # GET /secrets/1/edit
  def edit
  end

  # POST /secrets
  # POST /secrets.json
  def create
    @secret = Secret.new(secret_params)

    respond_to do |format|
      if @secret.save
        format.html { redirect_to @secret, notice: 'Secret was successfully created.' }
        format.json { render action: 'show', status: :created, location: @secret }
      else
        format.html { render action: 'new' }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secrets/1
  # PATCH/PUT /secrets/1.json
  def update
    respond_to do |format|
      if @secret.update(secret_params)
        format.html { redirect_to @secret, notice: 'Secret was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secrets/1
  # DELETE /secrets/1.json
  def destroy
    @secret.destroy
    respond_to do |format|
      format.html { redirect_to secrets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secret
      @secret = Secret.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secret_params
      params[:secret]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ouathdemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/secrets/_form.html.erb
<%= form_for(@secret) do |f| %>
  <% if @secret.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secret.errors.count, "error") %> prohibited this secret from being saved:</h2>

      <ul>
      <% @secret.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/secrets/edit.html.erb
<h1>Editing secret</h1>

<%= render 'form' %>

<%= link_to 'Show', @secret %> |
<%= link_to 'Back', secrets_path %>

app/views/secrets/index.html.erb
<h1>Listing secrets</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @secrets.each do |secret| %>
      <tr>
        <td><%= link_to 'Show', secret %></td>
        <td><%= link_to 'Edit', edit_secret_path(secret) %></td>
        <td><%= link_to 'Destroy', secret, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secret', new_secret_path %>

app/views/secrets/new.html.erb
<h1>New secret</h1>

<%= render 'form' %>

<%= link_to 'Back', secrets_path %>

app/views/secrets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_secret_path(@secret) %> |
<%= link_to 'Back', secrets_path %>